version: '2'
services:
  some-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

      # Create database on image startup.
      MYSQL_DATABASE: drupal7
    ports:
    - 3306
    volumes:
    - ../mysql:/var/lib/mysql
    - ./mysql/localdb-run.sh:/localdb-run.sh
    entrypoint: /localdb-run.sh

#  some-php:
#    image: php:5-apache
#    links:
#    - some-mysql:mysql
#    ports:
#    - '8080:80'
#      
  some-drupal:
    image: drupal:7
    volumes:
    - ../public_html:/var/www/html
    - ./php/php.ini:/usr/local/etc/php/php.ini
    links:
    - some-mysql:mysql
    depends_on:
    - some-mysql
    ports:
    - '8080:80'

