version: '2'
services:

  # Data-only container.
  data:
    image: busybox
    volumes:
    - ../volumes/drupal:/var/www/html

  # MySQL server.
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

      # Create database on image startup.
      MYSQL_DATABASE: drupal7
    ports:
    - 3306
    volumes:
    - ../volumes/mysql:/var/lib/mysql
    - ./localdb-run.sh:/localdb-run.sh

    # Run script to fix 'does not have access rights' error.
    # See https://github.com/docker-library/mysql/issues/99#issuecomment-145665645
    entrypoint: /localdb-run.sh

  # Drupal 7.
  web:
    build: .
    links:
    - mysql:mysql
    ports:
    - '8080:80'
    volumes_from:
    - data
    depends_on:
    - data
    - mysql

