version: '2'
services:

  # Data-only container. Do not remove, else MySQL data will disappear!
  data:
    image: busybox
    volumes:
    - ../volumes/drupal:/var/www/html
    # Share host Drush plugins with webserver Drush instance.
    - ${HOME}/.drush:/root/.drush
    - /var/lib/mysql

  # MySQL server.
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

      # Create database on image startup.
      MYSQL_DATABASE: drupal7
    ports:
    - 3306:3306
    volumes_from:
    - data
    volumes:
    # MySQL data files.
    # - ../volumes/mysql:/var/lib/mysql
    # Custom my.cnf.
    - ./my.cnf:/etc/mysql/conf.d/my.cnf
    # Script to fix 'does not have access rights' error.
    # - ./localdb-run.sh:/localdb-run.sh

    # Run script to fix 'does not have access rights' error.
    # See https://github.com/docker-library/mysql/issues/99#issuecomment-145665645
    # entrypoint: /localdb-run.sh

  # Drupal 7.
  web:
    build: .
    links:
    - mysql:mysql
    ports:
    - '80:80'
    - '8022:22'
    volumes_from:
    - data
    depends_on:
    - data
    - mysql

